-- Supreme Supabase Setup script for Kootmate Class 10 Syllabus Companion.
-- Copy and paste this script directly inside your Supabase SQL Editor.

-- NOTE: If your tables already exist but are missing columns (e.g. "role" under the users table), 
-- you can uncomment the drop lines below to perform a clean-slate reset:
-- DROP TABLE IF EXISTS content_items CASCADE;
-- DROP TABLE IF EXISTS chapters CASCADE;
-- DROP TABLE IF EXISTS subjects CASCADE;
-- DROP TABLE IF EXISTS classes CASCADE;
-- DROP TABLE IF EXISTS email_otps CASCADE;
-- DROP TABLE IF EXISTS users CASCADE;

-- 1. Create email_otps table
CREATE TABLE IF NOT EXISTS email_otps (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email TEXT NOT NULL,
  otp TEXT NOT NULL,
  expires_at TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Create users table
CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT UNIQUE NOT NULL,
  referral_code TEXT DEFAULT '',
  password TEXT DEFAULT '',
  selected_board TEXT DEFAULT 'cbse',
  google_id TEXT DEFAULT '',
  role TEXT DEFAULT 'student',
  avatar_url TEXT DEFAULT '',
  phone_number TEXT DEFAULT '',
  school_name TEXT DEFAULT '',
  dob TEXT DEFAULT '',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Safe patch for users who already created the 'users' table without the extra columns:
ALTER TABLE users ADD COLUMN IF NOT EXISTS role TEXT DEFAULT 'student';
ALTER TABLE users ADD COLUMN IF NOT EXISTS phone_number TEXT DEFAULT '';
ALTER TABLE users ADD COLUMN IF NOT EXISTS school_name TEXT DEFAULT '';
ALTER TABLE users ADD COLUMN IF NOT EXISTS dob TEXT DEFAULT '';

-- Enable Row Level Security (RLS)
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE email_otps ENABLE ROW LEVEL SECURITY;

-- Allow public access policies for free applet interactions
DROP POLICY IF EXISTS "Allow public select users" ON users;
CREATE POLICY "Allow public select users" ON users FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow public insert users" ON users;
CREATE POLICY "Allow public insert users" ON users FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public update users" ON users;
CREATE POLICY "Allow public update users" ON users FOR UPDATE USING (true);


DROP POLICY IF EXISTS "Allow public select email_otps" ON email_otps;
CREATE POLICY "Allow public select email_otps" ON email_otps FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow public insert email_otps" ON email_otps;
CREATE POLICY "Allow public insert email_otps" ON email_otps FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public delete email_otps" ON email_otps;
CREATE POLICY "Allow public delete email_otps" ON email_otps FOR DELETE USING (true);

-- 3. Create classes table
CREATE TABLE IF NOT EXISTS classes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  class_name TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Create subjects table
CREATE TABLE IF NOT EXISTS subjects (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  class_id BIGINT REFERENCES classes(id) ON DELETE CASCADE NOT NULL,
  subject_name TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Create chapters table
CREATE TABLE IF NOT EXISTS chapters (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  subject_id BIGINT REFERENCES subjects(id) ON DELETE CASCADE NOT NULL,
  chapter_name TEXT NOT NULL,
  description TEXT,
  mindmap_url TEXT,
  game_url TEXT,
  audio_url TEXT,
  pdf_url TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS for Educational Content Tables
ALTER TABLE classes ENABLE ROW LEVEL SECURITY;
ALTER TABLE subjects ENABLE ROW LEVEL SECURITY;
ALTER TABLE chapters ENABLE ROW LEVEL SECURITY;

-- Select policies (Allow anyone to view)
DROP POLICY IF EXISTS "Allow public select classes" ON classes;
CREATE POLICY "Allow public select classes" ON classes FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow public select subjects" ON subjects;
CREATE POLICY "Allow public select subjects" ON subjects FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow public select chapters" ON chapters;
CREATE POLICY "Allow public select chapters" ON chapters FOR SELECT USING (true);

-- Management policies (For development/pre-configured environments, allows full CRUD)
DROP POLICY IF EXISTS "Allow public insert classes" ON classes;
CREATE POLICY "Allow public insert classes" ON classes FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public update classes" ON classes;
CREATE POLICY "Allow public update classes" ON classes FOR UPDATE USING (true);

DROP POLICY IF EXISTS "Allow public delete classes" ON classes;
CREATE POLICY "Allow public delete classes" ON classes FOR DELETE USING (true);


DROP POLICY IF EXISTS "Allow public insert subjects" ON subjects;
CREATE POLICY "Allow public insert subjects" ON subjects FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public update subjects" ON subjects;
CREATE POLICY "Allow public update subjects" ON subjects FOR UPDATE USING (true);

DROP POLICY IF EXISTS "Allow public delete subjects" ON subjects;
CREATE POLICY "Allow public delete subjects" ON subjects FOR DELETE USING (true);


DROP POLICY IF EXISTS "Allow public insert chapters" ON chapters;
CREATE POLICY "Allow public insert chapters" ON chapters FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public update chapters" ON chapters;
CREATE POLICY "Allow public update chapters" ON chapters FOR UPDATE USING (true);

DROP POLICY IF EXISTS "Allow public delete chapters" ON chapters;
CREATE POLICY "Allow public delete chapters" ON chapters FOR DELETE USING (true);

-- 6. Create content_items table for the production Admin CMS
CREATE TABLE IF NOT EXISTS content_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  board TEXT NOT NULL,         -- 'CBSE' or 'SSC'
  subject TEXT NOT NULL,       -- e.g. 'Science'
  chapter TEXT NOT NULL,       -- e.g. 'Chemical Reactions'
  title TEXT NOT NULL,
  description TEXT,
  content_type TEXT NOT NULL,  -- 'mindmap' | 'pdf' | 'audio' | 'game'
  resource_url TEXT NOT NULL,
  thumbnail_url TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS for content_items
ALTER TABLE content_items ENABLE ROW LEVEL SECURITY;

-- Allow public read & write access
DROP POLICY IF EXISTS "Allow public select content_items" ON content_items;
CREATE POLICY "Allow public select content_items" ON content_items FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow public insert content_items" ON content_items;
CREATE POLICY "Allow public insert content_items" ON content_items FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public update content_items" ON content_items;
CREATE POLICY "Allow public update content_items" ON content_items FOR UPDATE USING (true);

DROP POLICY IF EXISTS "Allow public delete content_items" ON content_items;
CREATE POLICY "Allow public delete content_items" ON content_items FOR DELETE USING (true);


-- 7. INITIAL SEED DATA (Only inserted if they don't already exist)
-- This ensures your Supabase is immediately preloaded with class 10 boards, subjects, and chapters!

-- Inserting default Classes
INSERT INTO classes (id, class_name, created_at)
VALUES 
  (1, 'Class 10 CBSE', NOW()),
  (2, 'Class 10 SSC', NOW())
ON CONFLICT (id) DO NOTHING;

-- Reset identity sequence for classes to start past preloaded IDs
SELECT setval(pg_get_serial_sequence('classes', 'id'), COALESCE((SELECT MAX(id)+1 FROM classes), 1), false);

-- Inserting default Subjects
INSERT INTO subjects (id, class_id, subject_name, created_at)
VALUES
  -- CBSE
  (101, 1, 'Science 🧪', NOW()),
  (102, 1, 'Mathematics 📐', NOW()),
  (103, 1, 'Social Studies 🏛️', NOW()),
  -- SSC
  (201, 2, 'Science 1 (Physics/Chem) 🧪', NOW()),
  (202, 2, 'Science 2 (Biology/EVS) 🧬', NOW()),
  (203, 2, 'Mathematics Part 1 (Algebra) 📝', NOW()),
  (204, 2, 'Mathematics Part 2 (Geometry) 📐', NOW()),
  (205, 2, 'Social Sciences & Civics 🏛️', NOW())
ON CONFLICT (id) DO NOTHING;

-- Reset identity sequence for subjects to start past preloaded IDs
SELECT setval(pg_get_serial_sequence('subjects', 'id'), COALESCE((SELECT MAX(id)+1 FROM subjects), 1), false);

-- Inserting default Chapters
INSERT INTO chapters (id, subject_id, chapter_name, description, mindmap_url, game_url, audio_url, pdf_url, created_at)
VALUES
  (1001, 101, 'Chemical Reactions and Equations', 'Learn principles of chemical formulas, balancing equations, and redox reactions with molecular diagrams.', 'https://images.unsplash.com/photo-1603126857599-f6e157fa2fe6?q=80&w=600&auto=format&fit=crop', 'https://poki.com/en/g/refraction', 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3', 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf', NOW()),
  (1002, 102, 'Quadratic Equations', 'Master factorization, completing squares, discriminant calculations, and finding roots for CBSE guidelines.', 'https://images.unsplash.com/photo-1453733190148-c44698c26588?q=80&w=600&auto=format&fit=crop', 'https://www.coolmathgames.com', 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3', 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf', NOW()),
  (2001, 201, 'Gravitation', 'Understand Kepler''s laws of planetary motion, Newton''s gravity, escape velocity, and acceleration due to gravity (g).', 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?q=80&w=600&auto=format&fit=crop', 'https://www.coolmathgames.com', 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3', 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf', NOW())
ON CONFLICT (id) DO NOTHING;

-- Reset identity sequence for chapters to start past preloaded IDs
SELECT setval(pg_get_serial_sequence('chapters', 'id'), COALESCE((SELECT MAX(id)+1 FROM chapters), 1), false);



