-- Supreme Supabase Setup script for Kootmate Class 10 Syllabus Companion.
-- Copy and paste this script directly inside your Supabase SQL Editor.

-- NOTE: If your tables already exist but are missing columns (e.g. "role" under the users table), 
-- you can uncomment the drop lines below to perform a clean-slate reset:
-- DROP TABLE IF EXISTS content_items CASCADE;
-- DROP TABLE IF EXISTS chapters CASCADE;
-- DROP TABLE IF EXISTS subjects CASCADE;
-- DROP TABLE IF EXISTS classes CASCADE;
-- DROP TABLE IF EXISTS email_otps CASCADE;
-- DROP TABLE IF EXISTS users CASCADE;

-- 1. Create email_otps table
CREATE TABLE IF NOT EXISTS email_otps (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email TEXT NOT NULL,
  otp TEXT NOT NULL,
  expires_at TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Create users table
CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT UNIQUE NOT NULL,
  referral_code TEXT DEFAULT '',
  password TEXT DEFAULT '',
  selected_board TEXT DEFAULT 'cbse',
  google_id TEXT DEFAULT '',
  role TEXT DEFAULT 'student',
  avatar_url TEXT DEFAULT '',
  phone_number TEXT DEFAULT '',
  school_name TEXT DEFAULT '',
  dob TEXT DEFAULT '',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Safe patch for users who already created the 'users' table without the extra columns:
ALTER TABLE users ADD COLUMN IF NOT EXISTS role TEXT DEFAULT 'student';
ALTER TABLE users ADD COLUMN IF NOT EXISTS phone_number TEXT DEFAULT '';
ALTER TABLE users ADD COLUMN IF NOT EXISTS school_name TEXT DEFAULT '';
ALTER TABLE users ADD COLUMN IF NOT EXISTS dob TEXT DEFAULT '';

-- Enable Row Level Security (RLS)
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE email_otps ENABLE ROW LEVEL SECURITY;

-- Allow public access policies for free applet interactions
DROP POLICY IF EXISTS "Allow public select users" ON users;
CREATE POLICY "Allow public select users" ON users FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow public insert users" ON users;
CREATE POLICY "Allow public insert users" ON users FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public update users" ON users;
CREATE POLICY "Allow public update users" ON users FOR UPDATE USING (true);


DROP POLICY IF EXISTS "Allow public select email_otps" ON email_otps;
CREATE POLICY "Allow public select email_otps" ON email_otps FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow public insert email_otps" ON email_otps;
CREATE POLICY "Allow public insert email_otps" ON email_otps FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public delete email_otps" ON email_otps;
CREATE POLICY "Allow public delete email_otps" ON email_otps FOR DELETE USING (true);

-- 3. Create classes table
CREATE TABLE IF NOT EXISTS classes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  class_name TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Create subjects table
CREATE TABLE IF NOT EXISTS subjects (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  class_id BIGINT REFERENCES classes(id) ON DELETE CASCADE NOT NULL,
  subject_name TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Create chapters table
CREATE TABLE IF NOT EXISTS chapters (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  subject_id BIGINT REFERENCES subjects(id) ON DELETE CASCADE NOT NULL,
  chapter_name TEXT NOT NULL,
  description TEXT,
  mindmap_url TEXT,
  game_url TEXT,
  audio_url TEXT,
  pdf_url TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS for Educational Content Tables
ALTER TABLE classes ENABLE ROW LEVEL SECURITY;
ALTER TABLE subjects ENABLE ROW LEVEL SECURITY;
ALTER TABLE chapters ENABLE ROW LEVEL SECURITY;

-- Select policies (Allow anyone to view)
DROP POLICY IF EXISTS "Allow public select classes" ON classes;
CREATE POLICY "Allow public select classes" ON classes FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow public select subjects" ON subjects;
CREATE POLICY "Allow public select subjects" ON subjects FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow public select chapters" ON chapters;
CREATE POLICY "Allow public select chapters" ON chapters FOR SELECT USING (true);

-- Management policies (For development/pre-configured environments, allows full CRUD)
DROP POLICY IF EXISTS "Allow public insert classes" ON classes;
CREATE POLICY "Allow public insert classes" ON classes FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public update classes" ON classes;
CREATE POLICY "Allow public update classes" ON classes FOR UPDATE USING (true);

DROP POLICY IF EXISTS "Allow public delete classes" ON classes;
CREATE POLICY "Allow public delete classes" ON classes FOR DELETE USING (true);


DROP POLICY IF EXISTS "Allow public insert subjects" ON subjects;
CREATE POLICY "Allow public insert subjects" ON subjects FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public update subjects" ON subjects;
CREATE POLICY "Allow public update subjects" ON subjects FOR UPDATE USING (true);

DROP POLICY IF EXISTS "Allow public delete subjects" ON subjects;
CREATE POLICY "Allow public delete subjects" ON subjects FOR DELETE USING (true);


DROP POLICY IF EXISTS "Allow public insert chapters" ON chapters;
CREATE POLICY "Allow public insert chapters" ON chapters FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public update chapters" ON chapters;
CREATE POLICY "Allow public update chapters" ON chapters FOR UPDATE USING (true);

DROP POLICY IF EXISTS "Allow public delete chapters" ON chapters;
CREATE POLICY "Allow public delete chapters" ON chapters FOR DELETE USING (true);

-- 6. Create content_items table for the production Admin CMS
CREATE TABLE IF NOT EXISTS content_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  board TEXT NOT NULL,         -- 'CBSE' or 'SSC'
  subject TEXT NOT NULL,       -- e.g. 'Science'
  chapter TEXT NOT NULL,       -- e.g. 'Chemical Reactions'
  title TEXT NOT NULL,
  description TEXT,
  content_type TEXT NOT NULL,  -- 'mindmap' | 'pdf' | 'audio' | 'game'
  resource_url TEXT NOT NULL,
  thumbnail_url TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS for content_items
ALTER TABLE content_items ENABLE ROW LEVEL SECURITY;

-- Allow public read & write access
DROP POLICY IF EXISTS "Allow public select content_items" ON content_items;
CREATE POLICY "Allow public select content_items" ON content_items FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow public insert content_items" ON content_items;
CREATE POLICY "Allow public insert content_items" ON content_items FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public update content_items" ON content_items;
CREATE POLICY "Allow public update content_items" ON content_items FOR UPDATE USING (true);

DROP POLICY IF EXISTS "Allow public delete content_items" ON content_items;
CREATE POLICY "Allow public delete content_items" ON content_items FOR DELETE USING (true);


-- 7. INITIAL SEED DATA (Only inserted if they don't already exist)
-- This ensures your Supabase is immediately preloaded with class 10 boards, subjects, and chapters!

-- Inserting default Classes
INSERT INTO classes (id, class_name, created_at)
VALUES 
  (1, 'Class 10 CBSE', NOW()),
  (2, 'Class 10 SSC', NOW())
ON CONFLICT (id) DO NOTHING;

-- Reset identity sequence for classes to start past preloaded IDs
SELECT setval(pg_get_serial_sequence('classes', 'id'), COALESCE((SELECT MAX(id)+1 FROM classes), 1), false);

-- Inserting default Subjects
INSERT INTO subjects (id, class_id, subject_name, created_at)
VALUES
  -- CBSE
  (101, 1, 'Science 🧪', NOW()),
  (102, 1, 'Mathematics 📐', NOW()),
  (103, 1, 'Social Studies 🏛️', NOW()),
  -- SSC
  (201, 2, 'Science 1 (Physics/Chem) 🧪', NOW()),
  (202, 2, 'Science 2 (Biology/EVS) 🧬', NOW()),
  (203, 2, 'Mathematics Part 1 (Algebra) 📝', NOW()),
  (204, 2, 'Mathematics Part 2 (Geometry) 📐', NOW()),
  (205, 2, 'Social Sciences & Civics 🏛️', NOW())
ON CONFLICT (id) DO NOTHING;

-- Reset identity sequence for subjects to start past preloaded IDs
SELECT setval(pg_get_serial_sequence('subjects', 'id'), COALESCE((SELECT MAX(id)+1 FROM subjects), 1), false);

-- Inserting default Chapters
INSERT INTO chapters (id, subject_id, chapter_name, description, mindmap_url, game_url, audio_url, pdf_url, created_at)
VALUES
  (1001, 101, 'Chemical Reactions and Equations', 'Learn principles of chemical formulas, balancing equations, and redox reactions with molecular diagrams.', 'https://images.unsplash.com/photo-1603126857599-f6e157fa2fe6?q=80&w=600&auto=format&fit=crop', 'https://poki.com/en/g/refraction', 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3', 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf', NOW()),
  (1002, 102, 'Quadratic Equations', 'Master factorization, completing squares, discriminant calculations, and finding roots for CBSE guidelines.', 'https://images.unsplash.com/photo-1453733190148-c44698c26588?q=80&w=600&auto=format&fit=crop', 'https://www.coolmathgames.com', 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3', 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf', NOW()),
  (2001, 201, 'Gravitation', 'Understand Kepler''s laws of planetary motion, Newton''s gravity, escape velocity, and acceleration due to gravity (g).', 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?q=80&w=600&auto=format&fit=crop', 'https://www.coolmathgames.com', 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3', 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf', NOW())
ON CONFLICT (id) DO NOTHING;

-- Reset identity sequence for chapters to start past preloaded IDs
SELECT setval(pg_get_serial_sequence('chapters', 'id'), COALESCE((SELECT MAX(id)+1 FROM chapters), 1), false);

-- 8. SSC POLITICAL SCIENCE PATCHES (ALTER & INSERT COMMANDS FOR RECOVERY)
-- Paste these queries in your Supabase SQL Editor if you need to alter existing structures or seed new elements.

-- Alter table queries (if you want to rename or append columns dynamically on existing databases)
-- ALTER TABLE subjects ALTER COLUMN subject_name TYPE TEXT;
-- ALTER TABLE content_items ADD COLUMN IF NOT EXISTS is_free_preview BOOLEAN DEFAULT false;

-- Dynamic query to ensure Subject 205 (Social Sciences & Civics / Political Science) is in the database:
INSERT INTO subjects (id, class_id, subject_name, created_at)
VALUES (205, 2, 'Social Sciences & Civics 🏛️', NOW())
ON CONFLICT (id) DO UPDATE SET subject_name = EXCLUDED.subject_name;

-- Seed the 5 Political Science chapters directly under Subject 205 (SSC Social Sciences & Civics)
INSERT INTO chapters (id, subject_id, chapter_name, description, created_at)
VALUES 
  (2051, 205, 'Working of the Constitution', 'Learn about the working of the Indian Constitution, the framework of democracy, social justice, and judiciary roles.', NOW()),
  (2052, 205, 'The Electoral Process', 'Understand elections, electoral reforms, code of conduct, and the function of the Election Commission.', NOW()),
  (2053, 205, 'Political Parties', 'Study regional and national political party organizations, coalition structures, and dynamic political agendas in India.', NOW()),
  (2054, 205, 'Social and Political Movements', 'Examine consumer, environmental, workers, and tribal movements that shape public policy and democratic voices.', NOW()),
  (2055, 205, 'Challenges Faced by Indian Democracy', 'Analyze foundational, expansionary, and structural issues limiting complete democratic empowerment and civic equality.', NOW())
ON CONFLICT (id) DO NOTHING;

-- Reset identity sequence for chapters to start past preloaded IDs
SELECT setval(pg_get_serial_sequence('chapters', 'id'), COALESCE((SELECT MAX(id)+1 FROM chapters), 1), false);

-- ==========================================
-- SECURE SINGLE ACTIVE SESSION SYSTEM SCHEMAS
-- ==========================================

-- 1. Create active_sessions table
CREATE TABLE IF NOT EXISTS active_sessions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT REFERENCES users(id) ON DELETE CASCADE NOT NULL,
  session_token TEXT UNIQUE NOT NULL,
  is_active BOOLEAN DEFAULT true,
  device_name TEXT,
  browser TEXT,
  operating_system TEXT,
  ip_address TEXT,
  last_seen TIMESTAMPTZ DEFAULT NOW(),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  expires_at TIMESTAMPTZ
);

-- Enable Row Level Security (RLS) on active_sessions
-- By default, enabling RLS in PostgreSQL/Supabase blocks all access from non-superuser clients 
-- (such as anonymous/anon key clients or standard authenticated users) until policies are explicitly added.
ALTER TABLE active_sessions ENABLE ROW LEVEL SECURITY;

-- Clean up and drop any previously existing insecure permissive public policies.
-- This ensures that no public client has direct select, insert, update, or delete rights on this table.
DROP POLICY IF EXISTS "Allow public select active_sessions" ON active_sessions;
DROP POLICY IF EXISTS "Allow public insert active_sessions" ON active_sessions;
DROP POLICY IF EXISTS "Allow public update active_sessions" ON active_sessions;
DROP POLICY IF EXISTS "Allow public delete active_sessions" ON active_sessions;

-- To enforce maximum production security:
-- - We DO NOT define any public or authenticated RLS policies on active_sessions.
-- - Consequently, direct client-side operations (from the web browser using the anon key) are completely rejected.
-- - The table is accessed exclusively by our secure Express backend using the Supabase Service Role Key (which bypasses RLS).
-- - This protects all session tokens from being sniffed, created, or mutated by third-party clients.

-- 2. Atomic procedure to create/validate user session (handles race conditions and prevents multiple concurrent logins)
CREATE OR REPLACE FUNCTION create_user_session(
  p_user_id BIGINT,
  p_session_token TEXT,
  p_device_name TEXT,
  p_browser TEXT,
  p_operating_system TEXT,
  p_ip_address TEXT,
  p_expires_at TIMESTAMPTZ
) RETURNS JSON AS $$
DECLARE
  v_existing_id BIGINT;
  v_result JSON;
BEGIN
  -- Perform row-level lock on the specific user to eliminate any race conditions
  PERFORM id FROM users WHERE id = p_user_id FOR UPDATE;

  -- Search for any currently active session that hasn't timed out (sent heartbeat in last 2 mins)
  SELECT id INTO v_existing_id 
  FROM active_sessions 
  WHERE user_id = p_user_id 
    AND is_active = true 
    AND last_seen >= NOW() - INTERVAL '2 minutes'
    AND (expires_at IS NULL OR expires_at > NOW())
  LIMIT 1;

  IF v_existing_id IS NOT NULL THEN
    -- Active session already exists on another client device, login rejected
    v_result := json_build_object(
      'success', false,
      'code', 'ALREADY_LOGGED_IN',
      'message', 'This account is already logged in on another device. Please log out from that device before logging in.'
    );
  ELSE
    -- No active session exists. Invalidate any old stale sessions for this user
    UPDATE active_sessions 
    SET is_active = false 
    WHERE user_id = p_user_id;

    -- Insert new session record
    INSERT INTO active_sessions (
      user_id,
      session_token,
      is_active,
      device_name,
      browser,
      operating_system,
      ip_address,
      last_seen,
      created_at,
      expires_at
    ) VALUES (
      p_user_id,
      p_session_token,
      true,
      p_device_name,
      p_browser,
      p_operating_system,
      p_ip_address,
      NOW(),
      NOW(),
      p_expires_at
    );

    v_result := json_build_object(
      'success', true,
      'session_token', p_session_token
    );
  END IF;

  RETURN v_result;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 3. Atomic procedure to acknowledge heartbeat
CREATE OR REPLACE FUNCTION heartbeat_user_session(
  p_session_token TEXT
) RETURNS JSON AS $$
DECLARE
  v_session_id BIGINT;
  v_result JSON;
BEGIN
  -- Look up the session and verify it is active and not stale (> 2 mins)
  SELECT id INTO v_session_id
  FROM active_sessions
  WHERE session_token = p_session_token
    AND is_active = true
    AND last_seen >= NOW() - INTERVAL '2 minutes'
    AND (expires_at IS NULL OR expires_at > NOW())
  FOR UPDATE;

  IF v_session_id IS NULL THEN
    v_result := json_build_object(
      'success', false,
      'message', 'Session invalid, expired, or logged out.'
    );
  ELSE
    -- Session is valid, refresh last_seen timestamp
    UPDATE active_sessions
    SET last_seen = NOW()
    WHERE id = v_session_id;

    v_result := json_build_object(
      'success', true,
      'message', 'Heartbeat acknowledged.'
    );
  END IF;

  RETURN v_result;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 4. Atomic procedure to logout session
CREATE OR REPLACE FUNCTION logout_user_session(
  p_session_token TEXT
) RETURNS JSON AS $$
DECLARE
  v_session_id BIGINT;
  v_result JSON;
BEGIN
  SELECT id INTO v_session_id
  FROM active_sessions
  WHERE session_token = p_session_token
  FOR UPDATE;

  IF v_session_id IS NULL THEN
    v_result := json_build_object(
      'success', false,
      'message', 'Session not found.'
    );
  ELSE
    -- Deactivate the session
    UPDATE active_sessions
    SET is_active = false
    WHERE id = v_session_id;

    v_result := json_build_object(
      'success', true,
      'message', 'Logged out successfully.'
    );
  END IF;

  RETURN v_result;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;
